"""empty message

Revision ID: 620e72d94021
Revises: 25c41ddaacd1
Create Date: 2025-01-09 15:29:15.132882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620e72d94021'
down_revision = '25c41ddaacd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recover_password',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recover_password')
    # ### end Alembic commands ###
