"""empty message

Revision ID: 6ad61e868527
Revises: 052810af6c8d
Create Date: 2025-01-03 12:31:35.575032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad61e868527'
down_revision = '052810af6c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photoGal', sa.String(length=200), nullable=False))
        batch_op.drop_column('photo')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('photoGal')

    # ### end Alembic commands ###
