"""empty message

Revision ID: 940f6e110c50
Revises: e9930cd8bc0b
Create Date: 2025-01-23 13:28:45.862817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940f6e110c50'
down_revision = 'e9930cd8bc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
